consul:
  image: "consul"
  container_name: "consul"
  command: agent -dev -client=0.0.0.0

sinatra:
  container_name: "sinatra"
  build: .
  dockerfile: Dockerfile.example3
  links:
    - consul
  ports:
    - "4567:4567"

