#!/bin/bash

set -Eeu -o pipefail

_ensure_bundle() {
  if [ ! -d vendor/bundle ]; then
      bundle install --path vendor/bundle
  fi

  if [ Gemfile -nt vendor/bundle ]; then
      bundle
      touch vendor/bundle
  fi
}

build() {
  embedmd markdown.md > markdown.md.gen
}

test1() {
  _ensure_bundle
  bundle exec rspec spec/example1/example_spec.rb
}

test2() {
  _ensure_bundle
  bundle exec rspec spec/example2/example2_spec.rb
}

test3() {
  _ensure_bundle

  docker-compose build --no-cache
  bundle exec rspec spec/example3/example3_spec.rb
}

serve() {
  build

  python -m SimpleHTTPServer 8000 0.0.0.0
}

function task_usage {
  echo "Usage: $0 build | serve | test1 | test2 | test3"
  exit 1
}

CMD=${1:-}
shift || true
case ${CMD} in
  build) build ;;
  test1) test1 ;;
  test2) test2 ;;
  test3) test3 ;;
  serve) serve ;;
  *) task_usage ;;
esac
